version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aglet-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - aglet
    depends_on:
      - db
      - redis

  webserver:
    image: nginx:alpine
    container_name: aglet-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - aglet
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: aglet-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: aglet_backend
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: password
      MYSQL_USER: aglet_user
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - aglet

  redis:
    image: redis:alpine
    container_name: aglet-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - aglet

  node:
    image: node:18-alpine
    container_name: aglet-node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: sh -c "npm install && npm run dev"
    networks:
      - aglet

networks:
  aglet:
    driver: bridge

volumes:
  dbdata:
    driver: local 